image: Visual Studio 2015

environment:
  NODEJS_VERSION: "10"
  PREBUILD_UPLOAD:
    secure: r3xsm5djG7G5VQnfxWh40hvEzFcxG5AslPDQlOO1mT8U8BPRG3eeM82imZmBK0JU

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:Platform
  - node --version
  - npm --version
  - npm install

build: off

branches:
  only:
  - master
  - /^v?[0-9\\.]+/

test_script:
  - npm run test

deploy_script: IF "%APPVEYOR_REPO_TAG%" == "true" (npm run prebuild && npm run prebuild:upload -u %PREBUILD_UPLOAD%)